### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by masaeedu** [OneGet/nuget#1]
Some insight on what this repository is, why it is called nuget and contains credits for the original nuget project, how it differs from OneGet/NuGetProvider, and why there are two sln files: all of these would be very useful for anyone trying to understand the code.

**Comment by fearthecowboy** [comment]
Well, this repo is deprecated. 

It was the NuGet (and chocolatey) Provider for OneGet, and originally I forked and added the code; but that was getting to be a pain in the ass, so I rebuilt it (which is now the NuGetProvider) project. 

so, uh, ignore this now. :P
